server {
    listen 80;
    server_name localhost;

    # Раздача статики фронтенда
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
    }

    # Проксирование API запросов на бэкенд
    location /api {
        # Перенаправляем на сервис 'backend' на его внутренний порт 8000
        proxy_connect_timeout       300; # Время на установку соединения
        proxy_send_timeout          300; # Время на отправку запроса
        proxy_read_timeout          300; # Время на ожидание ответа (самое важное)
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}