# Файл: docker-compose.yml

version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: transneft-redis
    volumes:
      - redis_data:/data # Добавил том для сохранения данных Redis
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: transneft-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434" # Оставляем для отладки
    restart: unless-stopped

  backend:
    build:
      context: ./backend # Контекст сборки - папка backend
      args:
        - HF_TOKEN=${HF_TOKEN}
    container_name: transneft-backend
    ports: # Добавил порт для удобства прямого тестирования API
      - "8000:8000"
    volumes: # Добавил том для кэша моделей, чтобы не скачивать их каждый раз
      - models_cache:/root/.cache/huggingface
    environment:
      - REDIS_HOST=redis
      # --- ВОТ ГЛАВНОЕ ИСПРАВЛЕНИЕ ---
      # Передаем имя сервиса 'ollama' в контейнер backend
      - OLLAMA_HOST=ollama
      - XDG_CACHE_HOME=/root/.cache/huggingface
    depends_on:
      - redis
      - ollama
    restart: unless-stopped

  frontend:
    build: ./frontend # Контекст сборки - папка frontend
    container_name: transneft-frontend-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data:
  redis_data: # Объявил том для Redis
  models_cache: # Объявил том для кэша моделей