services:
  redis:
    image: redis:alpine
    container_name: transneft-redis
    restart: unless-stopped

  # --- НОВЫЙ СЕРВИС OLLAMA ---
  ollama:
    image: ollama/ollama
    container_name: transneft-ollama
    # Создаем именованный том, чтобы Ollama сохраняла скачанные модели между перезапусками
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Важно: Не пробрасываем порт 11434 наружу,
    # так как бэкенд будет общаться с ним по внутренней сети Docker.

  backend:
    build:
      context: ./backend
      args:
        - HF_TOKEN=${HF_TOKEN}
    container_name: transneft-backend
    environment:
      - REDIS_HOST=redis
    # --- ИЗМЕНЕНИЕ: Указываем зависимость от Ollama ---
    depends_on:
      - redis
      - ollama # Теперь бэкенд будет ждать, пока запустится Ollama
    restart: unless-stopped
    # Убираем extra_hosts, он больше не нужен
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: transneft-frontend-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

# --- НОВЫЙ РАЗДЕЛ: Объявляем именованный том ---
volumes:
  ollama_data: