services:
  redis:
    image: redis:alpine
    container_name: transneft-redis
    restart: unless-stopped

  ollama:
    # Просто используем официальный образ. Он сам запустит сервер.
    image: ollama/ollama
    container_name: transneft-ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      args:
        - HF_TOKEN=${HF_TOKEN}
    container_name: transneft-backend
    environment:
      - REDIS_HOST=redis
    depends_on:
      # Просто ждем, пока контейнеры redis и ollama запустятся.
      # Проверку наличия модели мы сделаем в коде бэкенда.
      - redis
      - ollama
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: transneft-frontend-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data: